[2024-09-13T12:55:12.726+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T12:55:15.723+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: correction_Dag_1FN.correct_1nf_violations scheduled__2024-09-13T12:50:00+00:00 [queued]>
[2024-09-13T12:55:15.891+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: correction_Dag_1FN.correct_1nf_violations scheduled__2024-09-13T12:50:00+00:00 [queued]>
[2024-09-13T12:55:15.907+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T12:55:16.311+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): correct_1nf_violations> on 2024-09-13 12:50:00+00:00
[2024-09-13T12:55:16.665+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'correction_Dag_1FN', 'correct_1nf_violations', 'scheduled__2024-09-13T12:50:00+00:00', '--job-id', '2214', '--raw', '--subdir', 'DAGS_FOLDER/Correction_dag_1FN.py', '--cfg-path', '/tmp/tmppnx6kxni']
[2024-09-13T12:55:16.764+0000] {standard_task_runner.py:105} INFO - Job 2214: Subtask correct_1nf_violations
[2024-09-13T12:55:16.882+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=88472) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T12:55:16.896+0000] {standard_task_runner.py:72} INFO - Started process 88501 to run task
[2024-09-13T12:55:23.994+0000] {task_command.py:467} INFO - Running <TaskInstance: correction_Dag_1FN.correct_1nf_violations scheduled__2024-09-13T12:50:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T12:55:25.652+0000] {job.py:229} INFO - Heartbeat recovered after 16.35 seconds
[2024-09-13T12:55:29.902+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='correction_Dag_1FN' AIRFLOW_CTX_TASK_ID='correct_1nf_violations' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T12:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T12:50:00+00:00'
[2024-09-13T12:55:29.916+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T12:55:32.615+0000] {logging_mixin.py:190} INFO - Erreur lors de la correction des anomalies : cannot drop table orders because other objects depend on it
DETAIL:  constraint orderdetails_order_id_fkey on table orderdetails depends on table orders
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
[2024-09-13T12:55:32.639+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T12:55:34.655+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T12:55:34.659+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=correction_Dag_1FN, task_id=correct_1nf_violations, run_id=scheduled__2024-09-13T12:50:00+00:00, execution_date=20240913T125000, start_date=20240913T125515, end_date=20240913T125534
[2024-09-13T12:55:34.863+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T12:55:35.620+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-13T12:55:37.136+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
