[2024-09-11T17:36:20.353+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T17:36:21.823+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_detect_excessively_high_total_amount.run_anomaly_detection scheduled__2024-09-11T17:15:00+00:00 [queued]>
[2024-09-11T17:36:21.904+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_detect_excessively_high_total_amount.run_anomaly_detection scheduled__2024-09-11T17:15:00+00:00 [queued]>
[2024-09-11T17:36:21.928+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-11T17:36:22.491+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-11 17:15:00+00:00
[2024-09-11T17:36:22.579+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=16008) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T17:36:22.592+0000] {standard_task_runner.py:72} INFO - Started process 16067 to run task
[2024-09-11T17:36:22.632+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_detect_excessively_high_total_amount', 'run_anomaly_detection', 'scheduled__2024-09-11T17:15:00+00:00', '--job-id', '1234', '--raw', '--subdir', 'DAGS_FOLDER/dag_detect_excessively_high_total_amount.py', '--cfg-path', '/tmp/tmpilkugfad']
[2024-09-11T17:36:22.659+0000] {standard_task_runner.py:105} INFO - Job 1234: Subtask run_anomaly_detection
[2024-09-11T17:36:25.756+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_detect_excessively_high_total_amount.run_anomaly_detection scheduled__2024-09-11T17:15:00+00:00 [running]> on host b8b5351e8a6b
[2024-09-11T17:36:29.594+0000] {job.py:229} INFO - Heartbeat recovered after 13.80 seconds
[2024-09-11T17:36:30.880+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_detect_excessively_high_total_amount' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T17:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T17:15:00+00:00'
[2024-09-11T17:36:30.891+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T17:36:31.036+0000] {dag_detect_excessively_high_total_amount.py:118} INFO - Starting anomaly detection process
[2024-09-11T17:36:38.332+0000] {dag_detect_excessively_high_total_amount.py:124} INFO - Loaded 15 transactions and 4 products
[2024-09-11T17:36:38.655+0000] {dag_detect_excessively_high_total_amount.py:127} INFO - Detected 0 anomalies
[2024-09-11T17:36:40.763+0000] {dag_detect_excessively_high_total_amount.py:111} INFO - Inserted 0 new anomalies.
[2024-09-11T17:36:40.766+0000] {dag_detect_excessively_high_total_amount.py:130} INFO - Anomaly detection process completed successfully
[2024-09-11T17:36:40.772+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-11T17:36:41.723+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T17:36:41.726+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_detect_excessively_high_total_amount, task_id=run_anomaly_detection, run_id=scheduled__2024-09-11T17:15:00+00:00, execution_date=20240911T171500, start_date=20240911T173621, end_date=20240911T173641
[2024-09-11T17:36:41.933+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-11T17:36:42.316+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T17:36:42.335+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-11T17:36:42.643+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
