[2024-09-13T15:30:12.194+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T15:30:12.712+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-13T15:25:00+00:00 [queued]>
[2024-09-13T15:30:12.747+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-13T15:25:00+00:00 [queued]>
[2024-09-13T15:30:12.749+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T15:30:12.793+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-13 15:25:00+00:00
[2024-09-13T15:30:12.862+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=13690) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T15:30:12.864+0000] {standard_task_runner.py:72} INFO - Started process 13764 to run task
[2024-09-13T15:30:12.866+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_Non-numeric-Quantity', 'run_anomaly_detection', 'scheduled__2024-09-13T15:25:00+00:00', '--job-id', '2657', '--raw', '--subdir', 'DAGS_FOLDER/Dag_Non-numeric-Quantity.py', '--cfg-path', '/tmp/tmp_xj_tha8']
[2024-09-13T15:30:12.874+0000] {standard_task_runner.py:105} INFO - Job 2657: Subtask run_anomaly_detection
[2024-09-13T15:30:14.410+0000] {task_command.py:467} INFO - Running <TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-13T15:25:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T15:30:15.484+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_Non-numeric-Quantity' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T15:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T15:25:00+00:00'
[2024-09-13T15:30:15.486+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T15:30:15.547+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T15:30:15.865+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T15:30:15.866+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Dag_Non-numeric-Quantity, task_id=run_anomaly_detection, run_id=scheduled__2024-09-13T15:25:00+00:00, execution_date=20240913T152500, start_date=20240913T153012, end_date=20240913T153015
[2024-09-13T15:30:15.964+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T15:30:16.234+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T15:30:16.239+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
