[2024-09-22T16:15:08.581+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T16:15:09.061+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-22T16:10:00+00:00 [queued]>
[2024-09-22T16:15:09.092+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-22T16:10:00+00:00 [queued]>
[2024-09-22T16:15:09.094+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-22T16:15:09.145+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-22 16:10:00+00:00
[2024-09-22T16:15:09.199+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=16617) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-22T16:15:09.202+0000] {standard_task_runner.py:72} INFO - Started process 16666 to run task
[2024-09-22T16:15:09.215+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_Non-numeric-Quantity', 'run_anomaly_detection', 'scheduled__2024-09-22T16:10:00+00:00', '--job-id', '5338', '--raw', '--subdir', 'DAGS_FOLDER/Dag_Non-numeric-Quantity.py', '--cfg-path', '/tmp/tmp38n84f7u']
[2024-09-22T16:15:09.248+0000] {standard_task_runner.py:105} INFO - Job 5338: Subtask run_anomaly_detection
[2024-09-22T16:15:10.477+0000] {task_command.py:467} INFO - Running <TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-22T16:10:00+00:00 [running]> on host 93b0c38322b3
[2024-09-22T16:15:11.789+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_Non-numeric-Quantity' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T16:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-22T16:10:00+00:00'
[2024-09-22T16:15:11.801+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T16:15:11.873+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-22T16:15:12.144+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T16:15:12.145+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Dag_Non-numeric-Quantity, task_id=run_anomaly_detection, run_id=scheduled__2024-09-22T16:10:00+00:00, execution_date=20240922T161000, start_date=20240922T161509, end_date=20240922T161512
[2024-09-22T16:15:12.217+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T16:15:12.531+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T16:15:12.538+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
