[2024-09-10T18:55:03.876+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T18:55:04.403+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: correction_Dag_Negative_Value.correct_negative_values scheduled__2024-09-10T18:50:00+00:00 [queued]>
[2024-09-10T18:55:04.493+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: correction_Dag_Negative_Value.correct_negative_values scheduled__2024-09-10T18:50:00+00:00 [queued]>
[2024-09-10T18:55:04.497+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-10T18:55:04.625+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): correct_negative_values> on 2024-09-10 18:50:00+00:00
[2024-09-10T18:55:04.699+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'correction_Dag_Negative_Value', 'correct_negative_values', 'scheduled__2024-09-10T18:50:00+00:00', '--job-id', '3193', '--raw', '--subdir', 'DAGS_FOLDER/Correction_dag_Negative_Value.py', '--cfg-path', '/tmp/tmpo0dq6nxt']
[2024-09-10T18:55:04.721+0000] {standard_task_runner.py:105} INFO - Job 3193: Subtask correct_negative_values
[2024-09-10T18:55:04.725+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8406) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T18:55:04.742+0000] {standard_task_runner.py:72} INFO - Started process 8425 to run task
[2024-09-10T18:55:06.365+0000] {task_command.py:467} INFO - Running <TaskInstance: correction_Dag_Negative_Value.correct_negative_values scheduled__2024-09-10T18:50:00+00:00 [running]> on host 5f241b76205c
[2024-09-10T18:55:08.196+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='correction_Dag_Negative_Value' AIRFLOW_CTX_TASK_ID='correct_negative_values' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T18:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-10T18:50:00+00:00'
[2024-09-10T18:55:08.201+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T18:55:08.744+0000] {logging_mixin.py:190} INFO - Anomalies corrigées avec succès.
[2024-09-10T18:55:08.745+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-10T18:55:09.206+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T18:55:09.208+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=correction_Dag_Negative_Value, task_id=correct_negative_values, run_id=scheduled__2024-09-10T18:50:00+00:00, execution_date=20240910T185000, start_date=20240910T185504, end_date=20240910T185509
[2024-09-10T18:55:09.339+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-10T18:55:09.778+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-10T18:55:09.830+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
