[2024-09-13T20:15:08.470+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T20:15:08.847+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Corrrect_Dag_detect_and_correct_collective_anomalie.detect_and_correct_collective_anomalie scheduled__2024-09-13T20:10:00+00:00 [queued]>
[2024-09-13T20:15:08.871+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Corrrect_Dag_detect_and_correct_collective_anomalie.detect_and_correct_collective_anomalie scheduled__2024-09-13T20:10:00+00:00 [queued]>
[2024-09-13T20:15:08.872+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T20:15:08.975+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): detect_and_correct_collective_anomalie> on 2024-09-13 20:10:00+00:00
[2024-09-13T20:15:09.015+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=58671) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T20:15:09.017+0000] {standard_task_runner.py:72} INFO - Started process 58726 to run task
[2024-09-13T20:15:09.017+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Corrrect_Dag_detect_and_correct_collective_anomalie', 'detect_and_correct_collective_anomalie', 'scheduled__2024-09-13T20:10:00+00:00', '--job-id', '3469', '--raw', '--subdir', 'DAGS_FOLDER/Corrrect_Dag_detect_and_correct_collective_anomalie.py', '--cfg-path', '/tmp/tmpyshtd4v2']
[2024-09-13T20:15:09.022+0000] {standard_task_runner.py:105} INFO - Job 3469: Subtask detect_and_correct_collective_anomalie
[2024-09-13T20:15:10.104+0000] {task_command.py:467} INFO - Running <TaskInstance: Corrrect_Dag_detect_and_correct_collective_anomalie.detect_and_correct_collective_anomalie scheduled__2024-09-13T20:10:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T20:15:11.762+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Corrrect_Dag_detect_and_correct_collective_anomalie' AIRFLOW_CTX_TASK_ID='detect_and_correct_collective_anomalie' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T20:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T20:10:00+00:00'
[2024-09-13T20:15:11.765+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T20:15:12.071+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/Corrrect_Dag_detect_and_correct_collective_anomalie.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-13T20:15:12.372+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T20:15:12.651+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T20:15:12.653+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Corrrect_Dag_detect_and_correct_collective_anomalie, task_id=detect_and_correct_collective_anomalie, run_id=scheduled__2024-09-13T20:10:00+00:00, execution_date=20240913T201000, start_date=20240913T201508, end_date=20240913T201512
[2024-09-13T20:15:12.752+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T20:15:13.068+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-13T20:15:14.023+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
