[2024-09-13T19:00:21.631+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T19:00:25.243+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-13T18:55:00+00:00 [queued]>
[2024-09-13T19:00:26.171+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-13T18:55:00+00:00 [queued]>
[2024-09-13T19:00:26.174+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T19:00:26.731+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-13 18:55:00+00:00
[2024-09-13T19:00:27.258+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_Non-numeric-Quantity', 'run_anomaly_detection', 'scheduled__2024-09-13T18:55:00+00:00', '--job-id', '3223', '--raw', '--subdir', 'DAGS_FOLDER/Dag_Non-numeric-Quantity.py', '--cfg-path', '/tmp/tmpgs3oxjzd']
[2024-09-13T19:00:27.534+0000] {standard_task_runner.py:105} INFO - Job 3223: Subtask run_anomaly_detection
[2024-09-13T19:00:28.200+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=46183) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T19:00:28.223+0000] {standard_task_runner.py:72} INFO - Started process 46269 to run task
[2024-09-13T19:02:07.747+0000] {job.py:229} INFO - Heartbeat recovered after 113.72 seconds
[2024-09-13T19:02:15.940+0000] {task_command.py:467} INFO - Running <TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-13T18:55:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T19:02:24.823+0000] {job.py:229} INFO - Heartbeat recovered after 20.46 seconds
[2024-09-13T19:02:32.895+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_Non-numeric-Quantity' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T18:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T18:55:00+00:00'
[2024-09-13T19:02:35.330+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T19:02:41.735+0000] {job.py:229} INFO - Heartbeat recovered after 18.40 seconds
[2024-09-13T19:02:42.919+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T19:02:46.888+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T19:02:46.960+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Dag_Non-numeric-Quantity, task_id=run_anomaly_detection, run_id=scheduled__2024-09-13T18:55:00+00:00, execution_date=20240913T185500, start_date=20240913T190025, end_date=20240913T190246
[2024-09-13T19:02:47.925+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T19:02:48.383+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-13T19:02:50.897+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T19:02:50.939+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
