[2024-09-13T19:25:05.670+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T19:25:06.219+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Corrrect_Dag_detect_and_correct_collective_anomalie.detect_and_correct_collective_anomalie scheduled__2024-09-13T19:20:00+00:00 [queued]>
[2024-09-13T19:25:06.258+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Corrrect_Dag_detect_and_correct_collective_anomalie.detect_and_correct_collective_anomalie scheduled__2024-09-13T19:20:00+00:00 [queued]>
[2024-09-13T19:25:06.261+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T19:25:06.363+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): detect_and_correct_collective_anomalie> on 2024-09-13 19:20:00+00:00
[2024-09-13T19:25:06.431+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=50048) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T19:25:06.434+0000] {standard_task_runner.py:72} INFO - Started process 50086 to run task
[2024-09-13T19:25:06.444+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Corrrect_Dag_detect_and_correct_collective_anomalie', 'detect_and_correct_collective_anomalie', 'scheduled__2024-09-13T19:20:00+00:00', '--job-id', '3306', '--raw', '--subdir', 'DAGS_FOLDER/Corrrect_Dag_detect_and_correct_collective_anomalie.py', '--cfg-path', '/tmp/tmppm6bkdpb']
[2024-09-13T19:25:06.449+0000] {standard_task_runner.py:105} INFO - Job 3306: Subtask detect_and_correct_collective_anomalie
[2024-09-13T19:25:07.548+0000] {task_command.py:467} INFO - Running <TaskInstance: Corrrect_Dag_detect_and_correct_collective_anomalie.detect_and_correct_collective_anomalie scheduled__2024-09-13T19:20:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T19:25:09.203+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Corrrect_Dag_detect_and_correct_collective_anomalie' AIRFLOW_CTX_TASK_ID='detect_and_correct_collective_anomalie' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T19:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T19:20:00+00:00'
[2024-09-13T19:25:09.212+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T19:25:09.584+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/Corrrect_Dag_detect_and_correct_collective_anomalie.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-13T19:25:10.293+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T19:25:10.655+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T19:25:10.657+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Corrrect_Dag_detect_and_correct_collective_anomalie, task_id=detect_and_correct_collective_anomalie, run_id=scheduled__2024-09-13T19:20:00+00:00, execution_date=20240913T192000, start_date=20240913T192506, end_date=20240913T192510
[2024-09-13T19:25:10.791+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T19:25:11.461+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-13T19:25:11.464+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
