[2024-09-11T17:50:19.029+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T17:50:19.960+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-11T17:45:00+00:00 [queued]>
[2024-09-11T17:50:20.048+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-11T17:45:00+00:00 [queued]>
[2024-09-11T17:50:20.059+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-11T17:50:20.357+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-11 17:45:00+00:00
[2024-09-11T17:50:20.467+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'detect_transaction_date_anomalies_dag', 'run_anomaly_detection', 'scheduled__2024-09-11T17:45:00+00:00', '--job-id', '1278', '--raw', '--subdir', 'DAGS_FOLDER/Dag-Transaction-Date-in-the-Paste.py', '--cfg-path', '/tmp/tmp5ccr_9fg']
[2024-09-11T17:50:20.474+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18354) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T17:50:20.477+0000] {standard_task_runner.py:105} INFO - Job 1278: Subtask run_anomaly_detection
[2024-09-11T17:50:20.479+0000] {standard_task_runner.py:72} INFO - Started process 18400 to run task
[2024-09-11T17:50:22.174+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-11T17:45:00+00:00 [running]> on host b8b5351e8a6b
[2024-09-11T17:50:23.943+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='detect_transaction_date_anomalies_dag' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T17:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T17:45:00+00:00'
[2024-09-11T17:50:23.952+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T17:50:24.745+0000] {Dag-Transaction-Date-in-the-Paste.py:97} INFO - Inserting 1 detected anomalies
[2024-09-11T17:50:26.128+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-11T17:50:26.280+0000] {job.py:229} INFO - Heartbeat recovered after 10.74 seconds
[2024-09-11T17:50:26.565+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T17:50:26.567+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_transaction_date_anomalies_dag, task_id=run_anomaly_detection, run_id=scheduled__2024-09-11T17:45:00+00:00, execution_date=20240911T174500, start_date=20240911T175019, end_date=20240911T175026
[2024-09-11T17:50:26.748+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-11T17:50:27.066+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T17:50:27.075+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
