[2024-09-12T12:40:18.160+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T12:40:18.540+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-12T12:35:00+00:00 [queued]>
[2024-09-12T12:40:18.573+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-12T12:35:00+00:00 [queued]>
[2024-09-12T12:40:18.575+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-12T12:40:18.651+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-12 12:35:00+00:00
[2024-09-12T12:40:18.793+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'detect_transaction_date_anomalies_dag', 'run_anomaly_detection', 'scheduled__2024-09-12T12:35:00+00:00', '--job-id', '1870', '--raw', '--subdir', 'DAGS_FOLDER/Dag-Transaction-Date-in-the-Paste.py', '--cfg-path', '/tmp/tmprzu5kf5t']
[2024-09-12T12:40:18.882+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=14815) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T12:40:18.898+0000] {standard_task_runner.py:105} INFO - Job 1870: Subtask run_anomaly_detection
[2024-09-12T12:40:18.901+0000] {standard_task_runner.py:72} INFO - Started process 14853 to run task
[2024-09-12T12:40:20.574+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-12T12:35:00+00:00 [running]> on host 7403e816bcf5
[2024-09-12T12:40:23.725+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='detect_transaction_date_anomalies_dag' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T12:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-12T12:35:00+00:00'
[2024-09-12T12:40:23.745+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T12:40:26.082+0000] {job.py:229} INFO - Heartbeat recovered after 12.26 seconds
[2024-09-12T12:40:28.451+0000] {Dag-Transaction-Date-in-the-Paste.py:97} INFO - Inserting 2 detected anomalies
[2024-09-12T12:40:29.220+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-12T12:40:30.141+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T12:40:30.148+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_transaction_date_anomalies_dag, task_id=run_anomaly_detection, run_id=scheduled__2024-09-12T12:35:00+00:00, execution_date=20240912T123500, start_date=20240912T124018, end_date=20240912T124030
[2024-09-12T12:40:30.410+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T12:40:30.907+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T12:40:30.914+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
