[2024-09-14T21:06:45.497+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-14T21:06:45.657+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-14T20:55:00+00:00 [queued]>
[2024-09-14T21:06:45.677+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-14T20:55:00+00:00 [queued]>
[2024-09-14T21:06:45.682+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-14T21:06:45.723+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-14 20:55:00+00:00
[2024-09-14T21:06:45.744+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2077) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-14T21:06:45.746+0000] {standard_task_runner.py:72} INFO - Started process 2084 to run task
[2024-09-14T21:06:45.744+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'detect_transaction_date_anomalies_dag', 'run_anomaly_detection', 'scheduled__2024-09-14T20:55:00+00:00', '--job-id', '4651', '--raw', '--subdir', 'DAGS_FOLDER/Dag-Transaction-Date-in-the-Paste.py', '--cfg-path', '/tmp/tmpr74rqjsp']
[2024-09-14T21:06:45.748+0000] {standard_task_runner.py:105} INFO - Job 4651: Subtask run_anomaly_detection
[2024-09-14T21:06:46.260+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-14T20:55:00+00:00 [running]> on host 7403e816bcf5
[2024-09-14T21:06:47.002+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='detect_transaction_date_anomalies_dag' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T20:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-14T20:55:00+00:00'
[2024-09-14T21:06:47.006+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-14T21:06:47.501+0000] {Dag-Transaction-Date-in-the-Paste.py:97} INFO - Inserting 2 detected anomalies
[2024-09-14T21:06:47.836+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-14T21:06:48.117+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-14T21:06:48.119+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_transaction_date_anomalies_dag, task_id=run_anomaly_detection, run_id=scheduled__2024-09-14T20:55:00+00:00, execution_date=20240914T205500, start_date=20240914T210645, end_date=20240914T210648
[2024-09-14T21:06:48.216+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-14T21:06:48.602+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-14T21:06:48.612+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
