[2024-09-12T14:00:05.529+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T14:00:06.671+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: correction_Dag_1FN.correct_1nf_violations scheduled__2024-09-12T13:55:00+00:00 [queued]>
[2024-09-12T14:00:06.921+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: correction_Dag_1FN.correct_1nf_violations scheduled__2024-09-12T13:55:00+00:00 [queued]>
[2024-09-12T14:00:06.935+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-12T14:00:07.924+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): correct_1nf_violations> on 2024-09-12 13:55:00+00:00
[2024-09-12T14:00:08.232+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'correction_Dag_1FN', 'correct_1nf_violations', 'scheduled__2024-09-12T13:55:00+00:00', '--job-id', '2038', '--raw', '--subdir', 'DAGS_FOLDER/Correction_dag_1FN.py', '--cfg-path', '/tmp/tmp4uusq3ls']
[2024-09-12T14:00:08.263+0000] {standard_task_runner.py:105} INFO - Job 2038: Subtask correct_1nf_violations
[2024-09-12T14:00:08.259+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28167) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T14:00:08.271+0000] {standard_task_runner.py:72} INFO - Started process 28203 to run task
[2024-09-12T14:00:12.046+0000] {task_command.py:467} INFO - Running <TaskInstance: correction_Dag_1FN.correct_1nf_violations scheduled__2024-09-12T13:55:00+00:00 [running]> on host 7403e816bcf5
[2024-09-12T14:00:20.348+0000] {job.py:229} INFO - Heartbeat recovered after 17.08 seconds
[2024-09-12T14:00:22.972+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='correction_Dag_1FN' AIRFLOW_CTX_TASK_ID='correct_1nf_violations' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T13:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-12T13:55:00+00:00'
[2024-09-12T14:00:22.996+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T14:00:24.018+0000] {logging_mixin.py:190} INFO - Erreur lors de la correction des anomalies : cannot drop table orders because other objects depend on it
DETAIL:  constraint orderdetails_order_id_fkey on table orderdetails depends on table orders
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
[2024-09-12T14:00:24.020+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-12T14:00:25.008+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T14:00:25.010+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=correction_Dag_1FN, task_id=correct_1nf_violations, run_id=scheduled__2024-09-12T13:55:00+00:00, execution_date=20240912T135500, start_date=20240912T140006, end_date=20240912T140025
[2024-09-12T14:00:25.451+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T14:00:27.119+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-12T14:00:34.127+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T14:00:34.238+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
