[2024-10-23T15:00:12.838+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T15:00:14.097+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-10-23T14:55:00+00:00 [queued]>
[2024-10-23T15:00:14.126+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-10-23T14:55:00+00:00 [queued]>
[2024-10-23T15:00:14.129+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-23T15:00:14.199+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-10-23 14:55:00+00:00
[2024-10-23T15:00:14.261+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=11208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-23T15:00:14.277+0000] {standard_task_runner.py:72} INFO - Started process 11268 to run task
[2024-10-23T15:00:14.293+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'detect_transaction_date_anomalies_dag', 'run_anomaly_detection', 'scheduled__2024-10-23T14:55:00+00:00', '--job-id', '6313', '--raw', '--subdir', 'DAGS_FOLDER/Dag-Transaction-Date-in-the-Paste.py', '--cfg-path', '/tmp/tmpau6bdw25']
[2024-10-23T15:00:14.316+0000] {standard_task_runner.py:105} INFO - Job 6313: Subtask run_anomaly_detection
[2024-10-23T15:00:16.913+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-10-23T14:55:00+00:00 [running]> on host 696ca67245ce
[2024-10-23T15:00:20.634+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='detect_transaction_date_anomalies_dag' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T14:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T14:55:00+00:00'
[2024-10-23T15:00:20.641+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T15:00:24.655+0000] {Dag-Transaction-Date-in-the-Paste.py:97} INFO - Inserting 2 detected anomalies
[2024-10-23T15:00:28.068+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-23T15:00:30.274+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T15:00:30.320+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_transaction_date_anomalies_dag, task_id=run_anomaly_detection, run_id=scheduled__2024-10-23T14:55:00+00:00, execution_date=20241023T145500, start_date=20241023T150014, end_date=20241023T150030
[2024-10-23T15:00:33.020+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-23T15:00:34.287+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-23T15:00:34.474+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T15:00:34.489+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
