[2024-09-14T21:00:12.907+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-14T21:00:14.772+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: correction_Dag_Valeu_NULL.correct_transactions_anomalies scheduled__2024-09-14T20:55:00+00:00 [queued]>
[2024-09-14T21:00:15.028+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: correction_Dag_Valeu_NULL.correct_transactions_anomalies scheduled__2024-09-14T20:55:00+00:00 [queued]>
[2024-09-14T21:00:15.040+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-14T21:00:16.023+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): correct_transactions_anomalies> on 2024-09-14 20:55:00+00:00
[2024-09-14T21:00:16.755+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1081) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-14T21:00:16.771+0000] {standard_task_runner.py:72} INFO - Started process 1122 to run task
[2024-09-14T21:00:18.043+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'correction_Dag_Valeu_NULL', 'correct_transactions_anomalies', 'scheduled__2024-09-14T20:55:00+00:00', '--job-id', '4596', '--raw', '--subdir', 'DAGS_FOLDER/Correction_dag_Valeur_NULL.py', '--cfg-path', '/tmp/tmpknyw_i1f']
[2024-09-14T21:00:20.036+0000] {standard_task_runner.py:105} INFO - Job 4596: Subtask correct_transactions_anomalies
[2024-09-14T21:00:26.214+0000] {job.py:229} INFO - Heartbeat recovered after 21.82 seconds
[2024-09-14T21:00:33.515+0000] {task_command.py:467} INFO - Running <TaskInstance: correction_Dag_Valeu_NULL.correct_transactions_anomalies scheduled__2024-09-14T20:55:00+00:00 [running]> on host 7403e816bcf5
[2024-09-14T21:00:36.977+0000] {job.py:229} INFO - Heartbeat recovered after 10.89 seconds
[2024-09-14T21:00:50.093+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='correction_Dag_Valeu_NULL' AIRFLOW_CTX_TASK_ID='correct_transactions_anomalies' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T20:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-14T20:55:00+00:00'
[2024-09-14T21:00:50.583+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-14T21:00:57.074+0000] {logging_mixin.py:190} INFO - Correction des anomalies dans la table Transactions r√©ussie.
[2024-09-14T21:00:57.097+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-14T21:00:58.067+0000] {job.py:229} INFO - Heartbeat recovered after 11.94 seconds
[2024-09-14T21:01:00.882+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-14T21:01:00.910+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=correction_Dag_Valeu_NULL, task_id=correct_transactions_anomalies, run_id=scheduled__2024-09-14T20:55:00+00:00, execution_date=20240914T205500, start_date=20240914T210014, end_date=20240914T210100
[2024-09-14T21:01:02.204+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-14T21:01:02.570+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-14T21:01:06.169+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
