[2024-09-13T22:50:27.497+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T22:50:28.282+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Corrrect_Dag_detect_and_correct_collective_anomalie.detect_and_correct_collective_anomalie scheduled__2024-09-13T22:45:00+00:00 [queued]>
[2024-09-13T22:50:28.314+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Corrrect_Dag_detect_and_correct_collective_anomalie.detect_and_correct_collective_anomalie scheduled__2024-09-13T22:45:00+00:00 [queued]>
[2024-09-13T22:50:28.316+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T22:50:28.380+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): detect_and_correct_collective_anomalie> on 2024-09-13 22:45:00+00:00
[2024-09-13T22:50:28.438+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=83396) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T22:50:28.443+0000] {standard_task_runner.py:72} INFO - Started process 83448 to run task
[2024-09-13T22:50:28.438+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Corrrect_Dag_detect_and_correct_collective_anomalie', 'detect_and_correct_collective_anomalie', 'scheduled__2024-09-13T22:45:00+00:00', '--job-id', '3878', '--raw', '--subdir', 'DAGS_FOLDER/Corrrect_Dag_detect_and_correct_collective_anomalie.py', '--cfg-path', '/tmp/tmp2xoxxbiw']
[2024-09-13T22:50:28.446+0000] {standard_task_runner.py:105} INFO - Job 3878: Subtask detect_and_correct_collective_anomalie
[2024-09-13T22:50:29.949+0000] {task_command.py:467} INFO - Running <TaskInstance: Corrrect_Dag_detect_and_correct_collective_anomalie.detect_and_correct_collective_anomalie scheduled__2024-09-13T22:45:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T22:50:31.762+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Corrrect_Dag_detect_and_correct_collective_anomalie' AIRFLOW_CTX_TASK_ID='detect_and_correct_collective_anomalie' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T22:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T22:45:00+00:00'
[2024-09-13T22:50:31.765+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T22:50:32.222+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/Corrrect_Dag_detect_and_correct_collective_anomalie.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-09-13T22:50:32.727+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T22:50:33.292+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T22:50:33.295+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Corrrect_Dag_detect_and_correct_collective_anomalie, task_id=detect_and_correct_collective_anomalie, run_id=scheduled__2024-09-13T22:45:00+00:00, execution_date=20240913T224500, start_date=20240913T225028, end_date=20240913T225033
[2024-09-13T22:50:33.408+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T22:50:33.450+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-13T22:50:33.833+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
