[2024-09-11T22:45:01.069+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T22:45:01.141+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: correction_Dag_Negative_Value.correct_negative_values scheduled__2024-09-11T22:40:00+00:00 [queued]>
[2024-09-11T22:45:01.151+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: correction_Dag_Negative_Value.correct_negative_values scheduled__2024-09-11T22:40:00+00:00 [queued]>
[2024-09-11T22:45:01.152+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-11T22:45:01.170+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): correct_negative_values> on 2024-09-11 22:40:00+00:00
[2024-09-11T22:45:01.179+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'correction_Dag_Negative_Value', 'correct_negative_values', 'scheduled__2024-09-11T22:40:00+00:00', '--job-id', '1582', '--raw', '--subdir', 'DAGS_FOLDER/Correction_dag_Negative_Value.py', '--cfg-path', '/tmp/tmpm5g443uj']
[2024-09-11T22:45:01.181+0000] {standard_task_runner.py:105} INFO - Job 1582: Subtask correct_negative_values
[2024-09-11T22:45:01.185+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=13657) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T22:45:01.186+0000] {standard_task_runner.py:72} INFO - Started process 13660 to run task
[2024-09-11T22:45:01.418+0000] {task_command.py:467} INFO - Running <TaskInstance: correction_Dag_Negative_Value.correct_negative_values scheduled__2024-09-11T22:40:00+00:00 [running]> on host 06814a36404b
[2024-09-11T22:45:01.807+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='correction_Dag_Negative_Value' AIRFLOW_CTX_TASK_ID='correct_negative_values' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T22:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T22:40:00+00:00'
[2024-09-11T22:45:01.810+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T22:45:01.908+0000] {logging_mixin.py:190} INFO - Anomalies corrigées avec succès.
[2024-09-11T22:45:01.909+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-11T22:45:01.997+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T22:45:01.997+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=correction_Dag_Negative_Value, task_id=correct_negative_values, run_id=scheduled__2024-09-11T22:40:00+00:00, execution_date=20240911T224000, start_date=20240911T224501, end_date=20240911T224501
[2024-09-11T22:45:02.047+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-11T22:45:02.152+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T22:45:02.157+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
